/**
 * Page catalog for the page-load smoke suite (tests/load).
 *
 * Generated from the qap sidebar menu on 15-09-2026 (every <a href> the
 * logged-in Admin sees). One entry per route, grouped by module in sidebar
 * order. Regenerate / extend by running the TC-LOAD-000 discovery test: it
 * lists any sidebar route that is missing here.
 *
 * Fields: module, name (menu caption), path (route), skip (optional reason -
 *         the page test is skipped with that reason).
 */
const PAGE_CATALOG = [
  // ---- Dashboard (1) ----
  { module: "Dashboard", name: "e-commerce", path: "/dsb/e-commerce" },
  // ---- Admin (35) ----
  { module: "Admin", name: "app-approval", path: "/adm/app-approval" },
  { module: "Admin", name: "Settings", path: "/adm/system-settings" },
  { module: "Admin", name: "Inventory Configuration", path: "/adm/app-inventory-configuration-setup" },
  { module: "Admin", name: "import template validation", path: "/adm/app-view-import-validation" },
  { module: "Admin", name: "Transaction Group Configuration", path: "/adm/view-transaction-group-configuration" },
  { module: "Admin", name: "Central Data Configuration", path: "/adm/central-data-repo-config" },
  { module: "Admin", name: "Discount Configuration", path: "/adm/view-discount-configuration-setup" },
  { module: "Admin", name: "Discount Scenario", path: "/adm/app-view-discount-scenario" },
  { module: "Admin", name: "Payment Mode Category", path: "/adm/view-payment-mode-category" },
  { module: "Admin", name: "DataSet Column Configuration", path: "/adm/dataset-column-configuration" },
  { module: "Admin", name: "Payment Mode Sub Category", path: "/adm/view-payment-mode-sub-category" },
  { module: "Admin", name: "Transaction Post Process Configuration", path: "/adm/app-view-transaction-post-process" },
  { module: "Admin", name: "Report Setup", path: "/adm/app-report-setup" },
  { module: "Admin", name: "Transaction Type", path: "/adm/transaction-type-setup" },
  { module: "Admin", name: "Password Policy", path: "/adm/view-pwd-policy" },
  { module: "Admin", name: "Roles", path: "/adm/view-roles" },
  { module: "Admin", name: "Users", path: "/adm/user-setup" },
  { module: "Admin", name: "Business Unit", path: "/adm/view-location" },
  { module: "Admin", name: "Organization Unit", path: "/adm/app-add-location-brand" },
  { module: "Admin", name: "Customer Classification", path: "/adm/app-view-customer-classification" },
  { module: "Admin", name: "Area", path: "/adm/view-geographical-setup" },
  { module: "Admin", name: "Action ShortCut Key", path: "/adm/app-action-shortcutkey" },
  { module: "Admin", name: "Print Configuration", path: "/adm/app-print-configuration-list" },
  { module: "Admin", name: "Master Data", path: "/adm/client-defined-masterdata" },
  { module: "Admin", name: "Functionality Settings", path: "/adm/view-functionality-settings" },
  { module: "Admin", name: "Format Template Builder", path: "/adm/view-format-template-builder" },
  { module: "Admin", name: "Documents", path: "/adm/document-type" },
  { module: "Admin", name: "File Upload Settings", path: "/adm/view-file-upload-settings-v2" },
  { module: "Admin", name: "Storage Provider", path: "/adm/view-storage-provider" },
  { module: "Admin", name: "Number Series", path: "/adm/app-number-series-setup-list" },
  { module: "Admin", name: "Setting Value", path: "/adm/keysettings-value" },
  { module: "Admin", name: "FTP", path: "/adm/view-ftp-settings" },
  { module: "Admin", name: "Printer", path: "/adm/app-printer-setup" },
  { module: "Admin", name: "Day End", path: "/adm/dayend-setup" },
  { module: "Admin", name: "Rate Master", path: "/adm/view-metal-rate-master" },
  // ---- Other (5) ----
  { module: "Other", name: "Admin (profile)", path: "/pages-profile", skip: "user-profile link, not a module screen; opening it drops the session (15-09-2026)" },
  { module: "Other", name: "Intellegence Insights", path: "/app-reports-home" },
  { module: "Other", name: "Barcode Design", path: "/barcode-template-list" },
  { module: "Other", name: "Print Builder", path: "/invoice-dashboard" },
  { module: "Other", name: "Report Builder", path: "/app-report-dashboard" },
  // ---- Intelligence Engine (16) ----
  { module: "Intelligence Engine", name: "Attribute", path: "/ite/ExtendedAttribute" },
  { module: "Intelligence Engine", name: "Attribute Value", path: "/ite/attribute-value" },
  { module: "Intelligence Engine", name: "Attribute Assignment Tran Type", path: "/ite/CustomControlTransactionTypeMapping" },
  { module: "Intelligence Engine", name: "Attribute Assignment Sub Type", path: "/ite/Custom-Control-Transaction-Sub-Type-Mapping" },
  { module: "Intelligence Engine", name: "Approval Category", path: "/ite/Approval-Category" },
  { module: "Intelligence Engine", name: "Approval Rule", path: "/ite/Approval-RuleMaster" },
  { module: "Intelligence Engine", name: "Approval Work Flow", path: "/ite/Approval-Work-Flow" },
  { module: "Intelligence Engine", name: "Approval Delegation", path: "/ite/Approval-Delegation" },
  { module: "Intelligence Engine", name: "Approval Committee", path: "/ite/Approval-Committee" },
  { module: "Intelligence Engine", name: "Contact Directory", path: "/ite/ContactDirectory" },
  { module: "Intelligence Engine", name: "Notification Rule", path: "/ite/NotificationTransactionRule" },
  { module: "Intelligence Engine", name: "Notification Work Flow", path: "/ite/Notification-Work-Flow" },
  { module: "Intelligence Engine", name: "Charges", path: "/ite/Additional-Charges" },
  { module: "Intelligence Engine", name: "Charges Template", path: "/ite/Additional-Charges-Template" },
  { module: "Intelligence Engine", name: "Charges Vendor Template", path: "/ite/Additional-Charges-Vendor-Template" },
  { module: "Intelligence Engine", name: "Pilot App Authenticator", path: "/ite/mobile-app-settings" },
  // ---- Procurement (19) ----
  { module: "Procurement", name: "Vendor Setup", path: "/prc/list-vendor-setup" },
  { module: "Procurement", name: "Vendor", path: "/prc/vendor-list" },
  { module: "Procurement", name: "Procurement Template", path: "/prc/view-template-master-list" },
  { module: "Procurement", name: "Vendor Wastage", path: "/prc/add-vendor-wastage" },
  { module: "Procurement", name: "Vendor Stone Rates", path: "/prc/add-vendor-stone-rate" },
  { module: "Procurement", name: "Alloy", path: "/prc/view-alloy" },
  { module: "Procurement", name: "Repair Wastage", path: "/prc/app-repair-wastage" },
  { module: "Procurement", name: "Alloy Inward", path: "/prc/view-alloy-inward" },
  { module: "Procurement", name: "Stone Assorting", path: "/prc/app-stone-assorting-list" },
  { module: "Procurement", name: "Stone Transaction", path: "/prc/app-stone-transaction" },
  { module: "Procurement", name: "Receipt", path: "/prc/app-repair-setup" },
  { module: "Procurement", name: "Internal Transfer", path: "/prc/internal-stock-list" },
  { module: "Procurement", name: "Issue", path: "/prc/view-samplejobwork-issue" },
  { module: "Procurement", name: "Purchase Return", path: "/prc/view-purchase-return" },
  { module: "Procurement", name: "Goods Receipt", path: "/prc/view-goods-receipt" },
  { module: "Procurement", name: "Logistic In / Out", path: "/prc/view-logistics" },
  { module: "Procurement", name: "Bullion Booking", path: "/prc/app-bullion-list" },
  { module: "Procurement", name: "Bullion Issue", path: "/prc/view-bullion-issue" },
  { module: "Procurement", name: "Stock Inward", path: "/prc/stock-inward-setup" },
  // ---- Inventory (18) ----
  { module: "Inventory", name: "Certification Stone Setup", path: "/inv/view-certification-stone-set-up" },
  { module: "Inventory", name: "Set Tag", path: "/inv/list-set-tag-setup" },
  { module: "Inventory", name: "Ageing Interval", path: "/inv/view-ageing-interval" },
  { module: "Inventory", name: "Counter", path: "/inv/counter-setup" },
  { module: "Inventory", name: "Barcode Series SetUp", path: "/inv/view-barcode-series-setup" },
  { module: "Inventory", name: "Vendor Design", path: "/inv/view-vendor-design-code-catalog" },
  { module: "Inventory", name: "Design Code", path: "/inv/design-code-variant-setup" },
  { module: "Inventory", name: "Description", path: "/inv/app-description-setup" },
  { module: "Inventory", name: "Article Setup", path: "/inv/view-article-setup" },
  { module: "Inventory", name: "Article", path: "/inv/list-article-setup" },
  { module: "Inventory", name: "Purity", path: "/inv/list-purity-setup" },
  { module: "Inventory", name: "Stone Setup", path: "/inv/app-side-stonesetup" },
  { module: "Inventory", name: "Stone", path: "/inv/view-stone-list" },
  { module: "Inventory", name: "UOM", path: "/inv/uom-setup" },
  { module: "Inventory", name: "Receipt", path: "/inv/app-receipt-list" },
  { module: "Inventory", name: "Lot Generation", path: "/inv/view-lot-generation" },
  { module: "Inventory", name: "Barcode", path: "/inv/view-barcode-generation" },
  { module: "Inventory", name: "Issue", path: "/inv/app-issue-list" },
  // ---- Production (17) ----
  { module: "Production", name: "Metal Stone Settings", path: "/prd/view-metal-stone-setting" },
  { module: "Production", name: "Smith / Karigar", path: "/prd/view-worker" },
  { module: "Production", name: "Category", path: "/prd/production-category-setup" },
  { module: "Production", name: "Wastage Loss", path: "/prd/wastage-loss-setup" },
  { module: "Production", name: "Wax To Metal Convert", path: "/prd/view-wax-to-metal-conversion-factor" },
  { module: "Production", name: "CAD", path: "/prd/app-cad-setup" },
  { module: "Production", name: "Concept", path: "/prd/view-concept" },
  { module: "Production", name: "Uploads", path: "/prd/view-uploads" },
  { module: "Production", name: "Approval", path: "/prd/view-approval" },
  { module: "Production", name: "Master Design", path: "/prd/view-master-design" },
  { module: "Production", name: "Job Assignment", path: "/prd/app-view-production-job-assignment" },
  { module: "Production", name: "Process Movement", path: "/prd/app-process-movement-setup" },
  { module: "Production", name: "Worker Settlement", path: "/prd/app-view-worker-settlement" },
  { module: "Production", name: "Job Works", path: "/prd/view-job-work" },
  { module: "Production", name: "Issue / Receipt", path: "/prd/app-worker-issue-receipt-setup" },
  { module: "Production", name: "Material Transaction", path: "/prd/production-material-transaction-list" },
  { module: "Production", name: "Job Finalize", path: "/prd/app-job-finalize-list" },
  // ---- Sales & Distribution (17) ----
  { module: "Sales & Distribution", name: "MRP Discount", path: "/sls/app-mrp-discount-setup" },
  { module: "Sales & Distribution", name: "Vendor Line Mapping", path: "/sls/app-add-vendor-line-mapping" },
  { module: "Sales & Distribution", name: "Template Master", path: "/sls/sales-template-setup" },
  { module: "Sales & Distribution", name: "Wastage", path: "/sls/customer-wastage" },
  { module: "Sales & Distribution", name: "Stone Rates", path: "/sls/customer-stone-rate" },
  { module: "Sales & Distribution", name: "Repair Registration", path: "/sls/view-repair-registration" },
  { module: "Sales & Distribution", name: "Approval Issue", path: "/sls/view-b2b-approval-issue" },
  { module: "Sales & Distribution", name: "Sample", path: "/sls/app-sample-setup" },
  { module: "Sales & Distribution", name: "Repair Delivery", path: "/sls/view-repair-delivery" },
  { module: "Sales & Distribution", name: "Sales Return", path: "/sls/view-b2b-metal-sales-return" },
  { module: "Sales & Distribution", name: "Approval Receipt", path: "/sls/view-approval-receipt" },
  { module: "Sales & Distribution", name: "Order", path: "/sls/order-booking" },
  { module: "Sales & Distribution", name: "Invoice", path: "/sls/app-invoice-setup" },
  { module: "Sales & Distribution", name: "Counter Accept", path: "/sls/view-counter-accept-reject" },
  { module: "Sales & Distribution", name: "Counter Transfer", path: "/sls/view-counter-transfer" },
  { module: "Sales & Distribution", name: "Counter Allocation", path: "/sls/view-counter-allocation" },
  { module: "Sales & Distribution", name: "Transfers", path: "/sls/view-transfer" },
  // ---- Retail Operations (8) ----
  { module: "Retail Operations", name: "Credit Limit Setup", path: "/pos/credit-limit" },
  { module: "Retail Operations", name: "Component Wastage Override", path: "/pos/wastage-component-override" },
  { module: "Retail Operations", name: "Unregister Purchase", path: "/pos/app-unregister-purchase" },
  { module: "Retail Operations", name: "Retail Wastage", path: "/pos/app-template-mapping-setup" },
  { module: "Retail Operations", name: "Stone Rates", path: "/pos/app-stone-rate-list" },
  { module: "Retail Operations", name: "Discounts", path: "/pos/app-discountsetup" },
  { module: "Retail Operations", name: "Estimations", path: "/pos/view-order-estimation" },
  { module: "Retail Operations", name: "Registrations", path: "/pos/view-order-advance-registration" },
  // ---- Finance (10) ----
  { module: "Finance", name: "Pos Card Machine Registration", path: "/fin/view-pos-card-machine-registration" },
  { module: "Finance", name: "Sub Payment Mode", path: "/fin/view-sub-payment-mode" },
  { module: "Finance", name: "Payment Mode", path: "/fin/view-payment-mode" },
  { module: "Finance", name: "UPI Generation", path: "/fin/view-upi-generation" },
  { module: "Finance", name: "Financial Year", path: "/fin/view-financial-year-setup" },
  { module: "Finance", name: "Currency", path: "/fin/currency-setup" },
  { module: "Finance", name: "Bank", path: "/fin/app-banksetup" },
  { module: "Finance", name: "Accounts", path: "/fin/app-account-list" },
  { module: "Finance", name: "Account Stock Group", path: "/fin/account-stock-group" },
  { module: "Finance", name: "Tax Engine", path: "/fin/view-tax-setup" },
  // ---- Layaway / EMA Plans (6) ----
  { module: "Layaway / EMA Plans", name: "LayawayPlan", path: "/ema/view-layaway-plan" },
  { module: "Layaway / EMA Plans", name: "Plan & Group", path: "/ema/view-advance-plan" },
  { module: "Layaway / EMA Plans", name: "Benefit", path: "/ema/app-benefit-template-setup" },
  { module: "Layaway / EMA Plans", name: "Incentive", path: "/ema/view-incentive-role" },
  { module: "Layaway / EMA Plans", name: "Enrollment & Collections", path: "/ema/app-enrollment-collection-setup" },
  { module: "Layaway / EMA Plans", name: "Closing & Payments", path: "/ema/view-adp-closing" },
  // ---- HRMS (2) ----
  { module: "HRMS", name: "Department", path: "/hrm/department-setup" },
  { module: "HRMS", name: "Employee", path: "/hrm/employee-setup" },
  // ---- CRM (1) ----
  { module: "CRM", name: "Customer Registration", path: "/crm/customer-list" },
  // ---- Reports (2) ----
  { module: "Reports", name: "Locker Day Book", path: "/rpt/app-reports-home/locker-day-book-standard" },
  { module: "Reports", name: "Production Day Book", path: "/rpt/app-reports-home/product-day-book-standard" },
];

module.exports = { PAGE_CATALOG };
